### PR TITLE
beta: Upgrade LTS Django

### PR DESCRIPTION
**Pull request by VerosK**
Consider upgrading django backend to upstream LTS version

### CODE REVIEW

**Comment by roidelapluie** [comment]
:+1:

**Comment by roidelapluie** [comment]
However I do not like >=1.8,<1.9

It makes the builds unreproducibles

**Comment by VerosK** [comment]
1.8.x should not introduce new features to 1.8, only bugfixes.

**Comment by roidelapluie** [comment]
Yes because new bugs never appear in subreleases? I think a best approach is to test if the deps are up to date in an automated way

**Pull request merged**
